### ISSUE TITLE
y axis for plot function for dendrogram different from R

### ISSUE THREAD

**Issue by nrkarthikeyan** [JuliaPlots/StatsPlots.jl#224] opened 2019-03-29 18:32 UTC
y axis for the plot function for dendrogram produced from hclust in Clustering.jl is different than that of R, even though the data structures are the same.

R code
*******
```
> a = c(0.333446, 0.616217, 0.952828, 0.455896, 0.22695, 0.302099, 0.335508, 0.131185)
> A = t(matrix(a, nrow = 2, ncol = 4, byrow=TRUE))
> hc <- hclust(dist(A), method="single")
> hc$height
[1] 0.1554508 0.2343383 0.3382649
> hc$merge
     [,1] [,2]
[1,]   -1   -4
[2,]   -2    1
[3,]   -3    2
> hc$order
[1] 3 2 1 4
> plot(hc)
```
<img width="682" alt="Screen Shot 2019-03-29 at 2 33 51 PM" src="https://user-images.githubusercontent.com/5995882/55254963-ad8ab500-522f-11e9-8ca8-9407651abfd5.png">

Julia code
**********
```
julia> using StatsPlots
julia> using Clustering
julia> using Distances
julia> a = [0.333446  0.616217  0.952828  0.455896
            0.22695   0.302099  0.335508  0.131185]
2×4 Array{Float64,2}:
 0.333446  0.616217  0.952828  0.455896
 0.22695   0.302099  0.335508  0.131185
julia> hc1 = hclust(pairwise(Euclidean(), a, a), :single)
Hclust{Float64}([-1 -4; -2 1; -3 2], [0.155451, 0.234338, 0.338265], [3, 2, 1, 4], :single)
julia> hc1.merges, hc1.order, hc1.heights
([-1 -4; -2 1; -3 2], [3, 2, 1, 4], [0.155451, 0.234338, 0.338265])
julia> plot(hc1)
```
<img width="584" alt="Screen Shot 2019-03-29 at 2 28 37 PM" src="https://user-images.githubusercontent.com/5995882/55254698-f2fab280-522e-11e9-97b1-f62bb0629ef4.png">

See the discrepancy in the y axes. The Julia plot is not showing the dendrogram heights properly.

Version info:
************
```
julia> versioninfo()

Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

julia> pkgs = Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 12 entries:
  "Distributions" => v"0.16.4"
  "StatsPlots"    => v"0.10.2"
  "MLDatasets"    => v"0.3.0"
  "PyCall"        => v"1.18.5"
  "HDF5"          => v"0.10.2"
  "CuArrays"      => v"0.8.1"
  "IJulia"        => v"1.15.2"
  "Distances"     => v"0.8.0"
  "Flux"          => v"0.6.7"
  "Plots"         => v"0.23.0"
  "RDatasets"     => v"0.6.1"
  "Clustering"    => v"0.12.2"
```

**Comment by piever** [comment] 2019-03-30 12:13
Pinging @kescobo as I think he wrote the recipe originally, I'm not familiar with the clustering algorithm / output enough to be sure what's going on.

**Comment by kescobo** [comment] 2019-03-30 14:36
Yeah, that's by design (not saying the design is correct...). 

The code [is here](https://github.com/JuliaPlots/StatsPlots.jl/blob/master/src/dendrogram.jl#L3-L13). Everything starts at `y=0`. At the moment, the `useheight` argument determines whether the branch lengths are used between levels, not where the branch starts. Eg `useheight=false`:

<img width="300" alt="Screen Shot 2019-03-30 at 10 26 54 AM" src="https://user-images.githubusercontent.com/3502975/55277417-5b509f00-52d6-11e9-834f-d8bf50681411.png">

vs the default `useheight=true`

<img width="300" alt="Screen Shot 2019-03-30 at 10 26 43 AM" src="https://user-images.githubusercontent.com/3502975/55277421-61df1680-52d6-11e9-9508-e96a98848727.png">

If you'd like to explain how to calculate where the branch should start on the y-axis given the hclust values, I'd be happy to help you with a PR to add that option. But from what I can tell, the R plotting isn't doing something any more principled, the vertical heights of all of branches are the same. Is there some mathematical reason for that?

I understand how branch lengths are important in something like a phylogeny where it says something about last common ancestor, but I don't know how that relates in hclust.

**Comment by nrkarthikeyan** [comment] 2019-04-01 14:00
Hi @piever and @kescobo. Thanks for the prompt comments. 

@kescobo, in R, the height at the merge of the leaf is exactly the same as the output height. From my previous example in R

```
> hc$height
[1] 0.1554508 0.2343383 0.3382649
```

You can see that this reflects the actual height. In Julia, it seems like the `height` field in the Hclust structure is the incremental height from the previous merge. Like you said, it does not matter sometimes, but I am trying to repurpose this code for something else and it matters in that application.

I am happy to do a PR to make Julia behavior compatible with R, but I have never done one before. So appreciate any help from you!

**Comment by kescobo** [comment] 2019-04-02 19:19
@nrkarthikeyan You're in for a treat! It feels so good to have a PR merged 😆. How familiar with git are you?

There are a lot of walkthroughs you can find with a quick search, but the basic steps are:

1. Fork the repository on github.
2. Clone your fork to your local computer
3. Make a new branch. Commit changes to this branch
4. When you push those commits to github, you'll see a button that says "create pull request". You can do this even before you're done (just make the title "[WIP] Something")
5. As you work, keep pushing commits to the same branch, and the PR will automatically update

If you haven't worked with git much, even those "basic" steps might trip you up, but I'm happy to help walk you through it - just tag me on the PR once you make it, or comment here if you get stuck before then.

**Closed** 2021-06-09 17:32 UTC
