### ISSUE TITLE
How to plot legend upside down in stacked groupedbar

### ISSUE THREAD

**Issue by ngphuoc** [JuliaPlots/StatsPlots.jl#140] opened 2018-04-13 07:54 UTC
It's is easier to see the legend and the stacked bars colors having the same order. Especially when there are many groups.

**Comment by mkborregaard** [comment] 2018-08-13 13:55
Yes, they should be the same color for sure. You can't specify it, but it should be built in.

**Comment by Lilyhanig** [comment] 2019-10-04 15:42
The problem is that the order is reverse to the way it get's stacked, they're listed top down, when generally bottom up is preferred for stacked bars.

**Comment by mkborregaard** [comment] 2019-10-04 15:50
Yes exactly. The order of colors in the bars should be reversed. It's a really nice first PR if anyone is interested.

**Comment by mkborregaard** [comment] 2020-02-29 08:59
Closed in #309

**Closed by mkborregaard** 2020-02-29 08:59 UTC
Labels: StatsPlots
